### PR TITLE
Update Scala to 3.0.0-RC1

### PR DESCRIPTION
**Pull request by aumann**
if #116 is merged before this, this one will boil down to just the last commit

### CODE REVIEW

**Comment by davesmith00000** [comment]
I've merged #116, do you want to rebase this one so we only have the one commit left?

**Comment by davesmith00000** [comment]
...and it looks like we're waiting on the circe release too.

**Comment by aumann** [comment]
Rebased - still waiting for circe-parser, though

**Comment by aumann** [comment]
looking good now that circe-parser is published

**Review by davesmith00000 — APPROVED** [review]
Thanks again!

**Comment by davesmith00000** [comment]
All merged, including into my current (200 commit) branch - all works perfectly. 👌

**Pull request merged**
